def commit(res):
    '''登录猫宁修改密码'''
    from selenium import webdriver
    import time
    driver = webdriver.Chrome(executable_path="./drivers/chromedriver")
    driver.maximize_window()
    time.sleep(3)
    driver.get("http://localhost:8080/morning/")
    time.sleep(3)
    driver.find_element_by_link_text("登录").click()
    time.sleep(3)
    driver.find_element_by_name("user.loginName").send_keys(res[0])
    driver.find_element_by_name("user.loginPassword").send_keys(res[1])
    time.sleep(3)
    try:
        driver.find_element_by_id("btn_login").click()
        time.sleep(3)
        driver.find_element_by_class_name("mian-nav-right-user").click()
    except:
        driver.quit()
        print("原账号或密码错误,无法登录，请重新输入！")
        exit()
    time.sleep(3)
    driver.find_element_by_link_text("个人中心").click()
    time.sleep(3)
    driver.window_handles
    driver.switch_to.window(driver.window_handles[1])
    driver.find_element_by_link_text("密码设置").click()
    time.sleep(3)
    driver.find_element_by_name("nowPassword").send_keys(res[1])
    driver.find_element_by_name("newPassword").send_keys(res[2])
    driver.find_element_by_name("confirmPwd").send_keys(res[2])
    time.sleep(3)
    driver.find_element_by_xpath("//*[@id='p_tCont']/div[3]/div/button[1]").click()
    time.sleep(3)
    driver.quit()
    '''用修改后的密码重新登录猫宁'''
    driver = webdriver.Chrome(executable_path="./drivers/chromedriver")
    driver.maximize_window()
    time.sleep(3)
    driver.get("http://localhost:8080/morning/")
    time.sleep(3)
    driver.find_element_by_link_text("登录").click()
    time.sleep(3)
    driver.find_element_by_name("user.loginName").send_keys(res[0])
    driver.find_element_by_name("user.loginPassword").send_keys(res[2])
    time.sleep(3)
    try:
        driver.find_element_by_id("btn_login").click()
        time.sleep(3)
        driver.find_element_by_class_name("mian-nav-right-user").click()
        time.sleep(3)
        driver.find_element_by_link_text("个人中心").click()
        time.sleep(3)
        driver.quit()
        print("密码修改成功，测试通过！")
        print("账号：",res[0],"原密码:",res[1],"新密码:",res[2])
    except:
        driver.quit()
        print("新密码不符合要求，请重新输入！")
        exit()
res = []
num0 = input("请输入账号：")
res.append(num0)
num1 = input("请输入原密码：")
res.append(num1)
num2 = input("请输入新密码：")
res.append(num2)
commit(res)