'''登录猫宁修改密码'''
from selenium import webdriver
import time
driver = webdriver.Chrome(executable_path="./drivers/chromedriver")
driver.maximize_window()
time.sleep(3)
driver.get("http://localhost:8080/morning/")
time.sleep(3)
driver.find_element_by_link_text("登录").click()
time.sleep(3)
driver.find_element_by_name("user.loginName").send_keys("18262620731")
driver.find_element_by_name("user.loginPassword").send_keys("zxcvbnm123")
time.sleep(3)
driver.find_element_by_id("btn_login").click()
time.sleep(3)
driver.find_element_by_class_name("mian-nav-right-user").click()
time.sleep(3)
driver.find_element_by_link_text("个人中心").click()
time.sleep(3)
driver.window_handles
driver.switch_to.window(driver.window_handles[1])
driver.find_element_by_link_text("密码设置").click()
time.sleep(3)
driver.find_element_by_name("nowPassword").send_keys("zxcvbnm123")
driver.find_element_by_name("newPassword").send_keys("zxcvbnm1234")
driver.find_element_by_name("confirmPwd").send_keys("zxcvbnm1234")
time.sleep(3)
driver.find_element_by_xpath("//*[@id='p_tCont']/div[3]/div/button[1]").click()
time.sleep(3)
driver.quit()
'''用修改后的密码重新登录猫宁'''
driver = webdriver.Chrome(executable_path="./drivers/chromedriver")
driver.maximize_window()
time.sleep(3)
driver.get("http://localhost:8080/morning/")
time.sleep(3)
driver.find_element_by_link_text("登录").click()
time.sleep(3)
driver.find_element_by_name("user.loginName").send_keys("18262620731")
driver.find_element_by_name("user.loginPassword").send_keys("zxcvbnm1234")
time.sleep(3)
driver.find_element_by_id("btn_login").click()
time.sleep(3)
driver.quit()